name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    uses: lexmag/elixir-actions/.github/workflows/lint.yml@v2
    with:
      otp-version: "27"
      elixir-version: "1.20"

  test:
    name: Test suite
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        versions:
          - elixir: "1.12"
            otp: "24"
          - elixir: "1.20"
            otp: "29"

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v7

      - name: Set up Elixir environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          otp-version: ${{ matrix.versions.otp }}

      - name: Install dependencies
        run: mix deps.get --only test

      - run: mix test
